version: '3.5'

services:
  aaxistest-php81-symfony54:
    container_name: aaxistest-php81-symfony54
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
    ports:
      - '1000:8000'
    networks:
      - aaxistest-php81-symfony54-network
    depends_on:
      - aaxistest-php81-symfony54-postgres

  aaxistest-php81-symfony54-postgres:
    container_name: aaxistest-php81-symfony54-postgres
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: postgres_symfony
    volumes:
      - aaxistest-php81-symfony54-pgsql-data:/var/lib/postgresql/data
    networks:
      - aaxistest-php81-symfony54-network

networks:
  aaxistest-php81-symfony54-network:

volumes:
  aaxistest-php81-symfony54-pgsql-data:
